// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbspmljZMNrMxylC51qtx0Kt9oQUiHqY',
    appId: '1:9296122063:web:6381e8f1fd780e01faa7ba',
    messagingSenderId: '9296122063',
    projectId: 'inplace-f3020',
    authDomain: 'inplace-f3020.firebaseapp.com',
    storageBucket: 'inplace-f3020.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIL4qoramkFdroSEXbChoLdt6WVv6uQqU',
    appId: '1:9296122063:android:97e36c6933ea8744faa7ba',
    messagingSenderId: '9296122063',
    projectId: 'inplace-f3020',
    storageBucket: 'inplace-f3020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9h_0QfZTGLyPKQwpAKgxv6819apNb84M',
    appId: '1:9296122063:ios:87148ffb06f780e1faa7ba',
    messagingSenderId: '9296122063',
    projectId: 'inplace-f3020',
    storageBucket: 'inplace-f3020.appspot.com',
    iosClientId: '9296122063-5qc0u9hjnj5hf51mf9pqq6s4dakcl9dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.inplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9h_0QfZTGLyPKQwpAKgxv6819apNb84M',
    appId: '1:9296122063:ios:87148ffb06f780e1faa7ba',
    messagingSenderId: '9296122063',
    projectId: 'inplace-f3020',
    storageBucket: 'inplace-f3020.appspot.com',
    iosClientId: '9296122063-5qc0u9hjnj5hf51mf9pqq6s4dakcl9dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.inplace',
  );
}
